### ISSUE TITLE
این ارور تو اندروید نسخه 11 پیش میاد و هیچ نوتی دریافت و نشون داده نمیشه 

### ISSUE THREAD

**Issue by afrazakhavan** [push-pole/android-studio-sample#15]
E/PushPole: Error occurred in PushPoleProvider
    java.lang.NullPointerException: Attempt to read from field 'java.lang.Thread$UncaughtExceptionHandler com.pushpole.sdk.internal.log.a.c' on a null object reference
        at com.pushpole.sdk.internal.log.a.b(Unknown Source:2)
        at com.pushpole.sdk.provider.PushPoleProvider.onCreate(Unknown Source:14)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2411)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2381)
        at androidx.core.content.FileProvider.attachInfo(FileProvider.java:409)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7443)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6922)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6817)
        at android.app.ActivityThread.access$1400(ActivityThread.java:244)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1951)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:7861)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by mhmpour** [comment]
منم موقعی که نسخه پوش پل رو 1.7.8 کردم و بعد یک ساعت از بستن اپلیکیشن نوت یا جیسون ارسال کردم با این خطا مواجه میشم
