### ISSUE TITLE
java.lang.NoClassDefFoundError: okhttp3/internal/platform/Platform

### ISSUE THREAD

**Issue by mhoseini967** [push-pole/android-studio-sample#2]
this problem just happen on android version 4 
version of library : 1.7.7
Error1:
A/PushPole: Exception caught 
    java.lang.NoClassDefFoundError: okhttp3/internal/platform/Platform
        at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:224)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:216)
Error2:
A/PushPole: Exception caught 
    java.lang.RuntimeException: Unable to start activity ComponentInfo{ir.hicodes.hoseinie/ir.hicodes.hoseinie.MainActivity}: android.view.InflateException: Binary XML file line #234: Error inflating class ImageView

**Comment by mhmmdyldi** [comment]
Your first error just has been caught by Pushpole SDK, and literally Pushpole SDK didn't cause this problem and this is not about our SDK.
Please give more information about second issue, write more details about the error, condition or scenario cause this problem.
