### ISSUE TITLE
Failed to receive push notification

### ISSUE THREAD

**Issue by javaherisaber** [push-pole/android-studio-sample#5]
I'm having difficulty receiving push notification on my devices
here is the stack trace of logcat error:

`E/PushPole: Obtaining FCM token failed: java.io.IOException: FIS_AUTH_ERROR
    java.util.concurrent.ExecutionException: java.io.IOException: FIS_AUTH_ERROR
        at com.google.android.gms.tasks.Tasks.zzb(Unknown Source:61)
        at com.google.android.gms.tasks.Tasks.await(Unknown Source:23)
        at com.pushpole.sdk.task.tasks.a.a(Unknown Source:31)
        at com.pushpole.sdk.task.e.a(Unknown Source:87)
        at com.pushpole.sdk.task.b.a.a.onRunJob(Unknown Source:24)
        at com.evernote.android.job.Job.runJob(Job.java:124)
        at com.evernote.android.job.JobExecutor$JobCallable.runJob(JobExecutor.java:181)
        at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:166)
        at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:149)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.io.IOException: FIS_AUTH_ERROR
        at com.google.firebase.iid.zzu.then(com.google.firebase:firebase-iid@@20.1.5:16)
        at com.google.android.gms.tasks.zzd.run(Unknown Source:5)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.android.gms.common.util.concurrent.zza.run`

### Pushe version = 1.7.1

**Comment by yousefabd1** [comment]
According to your push-pole panel, there is no registration for your applications, except two.
This problem occurs because of using 20.1.1 and upper versions of firebase-messaging library. According to our [documents ](https://docs.push-pole.com/docs/android-studio/#firebase) you have to use 20.1.0 or lower version of this library. 
implementation "com.google.firebase:firebase-messaging:20.1.0"
